apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.coordinator" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
data:
  node.properties: |
    node.environment={{ .Values.server.node.environment }}
    node.data-dir={{ .Values.server.node.dataDir }}
    plugin.dir={{ .Values.server.node.pluginDir }}

  jvm.config: |
    -server
    -Xmx{{ .Values.server.jvm.maxHeapSize }}
    -XX:+{{ .Values.server.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.server.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    {{ if .Values.exporters.jmx.enabled }}
    -Dcom.sun.management.jmxremote=true
    -Dcom.sun.management.jmxremote.local.only=false
    -Dcom.sun.management.jmxremote.authenticate=false
    -Dcom.sun.management.jmxremote.ssl=false
    -Dcom.sun.management.jmxremote.port={{ .Values.server.jmx.registryPort }}
    -Dcom.sun.management.jmxremote.rmi.port={{ .Values.server.jmx.serverPort }}
    -javaagent:/usr/lib/trino/lib/jmx_prometheus_javaagent-0.16.0.jar={{ .Values.exporters.jmx.port }}:{{ .Values.exporters.jmx.mountpath }}
    {{ end }}
    {{ range $value := .Values.server.jvm.additional_params }}
    {{ $value }}
    {{end}}

  config.properties: |
    coordinator=true
{{- if gt (int .Values.server.workers) 0 }}
    node-scheduler.include-coordinator=false
{{- else }}
    node-scheduler.include-coordinator=true
{{- end }}
    http-server.http.port={{ .Values.server.config.http.port }}
    query.max-memory={{ .Values.server.config.query.maxMemory }}
    query.max-total-memory={{ .Values.server.config.query.maxTotalMemory }}
    query.max-memory-per-node={{ .Values.server.config.query.maxMemoryPerNode }}

    discovery.uri=http://localhost:{{ .Values.server.config.http.port }}
    {{ if .Values.server.config.https.enabled }}
    http-server.https.enabled=true
    http-server.https.port={{ .Values.server.config.https.port }}
    http-server.https.keystore.path={{ .Values.keystore.filepath }}
    http-server.https.keystore.key={{ .Values.keystore.key }}
    http-server.authentication.type=PASSWORD
    {{end }}
    {{ if .Values.exporters.jmx.enabled }}
    jmx.rmiregistry.port={{ .Values.server.jmx.registryPort }}
    jmx.rmiserver.port={{ .Values.server.jmx.serverPort }}
    {{ end }}
    {{ range $key,$value := .Values.server.config.additional_params }}
    {{ $key }}={{ $value }}
  {{end}}
  log.properties: |
    io.trino={{ .Values.server.log.trino.level }}
{{ if .Values.server.config.https.enabled }}
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file={{ .Values.passwordfile.filepath }}
  access-control.properties: |
    access-control.name=file
    security.config-file=etc/rules.json
    security.refresh-period=10s
  rules.json: |
    {
     "catalogs": [
        {
          "user": "(trino)",
          "catalog": "(hive|system)",
          "allow": "all"
        }
     ],
     "tables": [
        {
          "user": "test",
          "catalog": "system",
          "schema": "jdbc",
          "privileges": ["SELECT"]
        }
     ]
    }
{{end}}
---
